package io.github.ilia_kulakov;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.springframework.boot.SpringApplication;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.context.annotation.ComponentScan;

@SpringBootConfiguration
@EnableAutoConfiguration
@ComponentScan("io.github.ilia_kulakov")
public class App {


    public static void main(String[] args) {
        SpringApplication.run(App.class, args);

    }
}


