package io.github.ilia_kulakov;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.springframework.boot.SpringApplication;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootConfiguration
@EnableAutoConfiguration
@ComponentScan("io.github.rmuhamedgaliev")
public class App {


    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}

//public class App {
   /*public String getGreeting() {
        return "Hello world 3.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }*/
//}
