package io.github.personal_finance;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.springframework.boot.SpringApplication;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import io.github.personal_finance.domain.Category;
import io.github.personal_finance.domain.Expence;
import io.github.personal_finance.domain.User;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.springframework.data.jpa.provider.HibernateUtils;

import javax.persistence.Query;

@SpringBootConfiguration
@SpringBootApplication(scanBasePackages = "io.github.personal_finance")
public class App {

    public static void main(String[] args) {

        SpringApplication.run(App.class, args);





    }
}


