package io.github.personal_finance;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.springframework.boot.SpringApplication;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;

//import org.springframework.context.annotation.Configuration;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootConfiguration
@SpringBootApplication(scanBasePackages = "io.github.personal_finance")
//@ComponentScan("io.github.ilia_kulakov")
public class App {

    public static void main(String[] args) {

        // SessionFactory sessionFactory = HibernateUtil.getSessionFactory();

        // Session session = sessionFactory.openSession();
        // Transaction tx = session.beginTransaction();
        //  session.close();

        SpringApplication.run(App.class, args);

       /* SessionFactory sessionFactory =
                new Configuration()
                        .configure()
                        .buildSessionFactory();

        Session session = sessionFactory.openSession();*/


    }
}


